name: action-workflow

on: [push]

jobs:
    run-github-actions:
       runs-on: ubuntu-latest
       steps:
          - name: simple JS greeting
            id: greeting
            uses: actions/hello-world-javascript-action@v1
            with:
              who-to-greet: Garry
          - name: greeting output
            run: echo "{{steps.greeting.outputs.time}}"


