name: action-workflow

on: [push]

jobs:
    run-github-actions:
       runs-on: ubuntu-latest
       steps:
          - name: List of files
            run: |
              pwd
              ls -a
          - name: checkout
            uses: actions/checkout@v1
          - name: List of files fter check output
            run: |
              pwd
              ls -a      
          - name: simple JS greeting
            id: greeting
            uses: actions/hello-world-javascript-action@v1
            with:
              who-to-greet: Garry
          - name: greeting output
            run: echo "{{steps.greeting.outputs.time}}"


